name: Lint

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags-ignore:
      - v*           # Push events to tags v*

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.0
